### PR TITLE
Improve README files

### PR DESCRIPTION
**Pull request by Enet4**
- Update authors section
- Add citation to paper on the architecture of Dicoogle
- Provide pointers to plugin development and Dicoogle core development
- Provide pointers for contributing to Dicoogle
- Add information in webapp README for debugging
- Prettify and reorganize some of the readme content

### CODE REVIEW

**Comment by jorgeMFS** [comment]
I'd put the section on how to build the jar bellow the official web site. Also I thinks that the build instructions are not at all clear.

**Comment by Enet4** [comment]
@jorgeMFS I've added the requirements to that sections. Please have a look now.

**Comment by jorgeMFS** [comment]
Seems ok now. I  suggest a link to the build a jar instructions on the beginning of the read me instead of placing all the building content after the dicoogle project description @Enet4.

**Comment by Enet4** [comment]
@jorgeMFS See if commit f7c8756 helps.

**Pull request merged**
