### PR TITLE
Add CORS support to Dicoogle web services

### PR DESCRIPTION
**Pull request by Enet4**
This adds support to Cross-Origin Resource Sharing, so that web browser applications may perform cross-origin requests to these services.

### CODE REVIEW

**Comment by bastiao** [comment]
@tmgodinho since we will deprecate the RESTlet web services, should stop allowing modifications on that? 
@fredericojssilva what are the status of web services implementation in Jetty?

**Comment by Enet4** [comment]
I honestly didn't know they were going to become deprecated, but it appears to be what we currently have. In addition, I had to add CORS support for the JavaScript web service access wrapper.

**Comment by Enet4** [comment]
I will close this PR for now, as it could bring some safety issues. Hopefully, this will be addressed in the new implementation.

**Comment by bastiao** [comment]
Can you fix it in the Jetty? 
Instead of allow it from all, we can allow for a specific domain.

**Comment by Enet4** [comment]
I haven't looked into the new implementations at all so far. But yes, specifying accepted cross-origin domains would become a requirement.

**Pull request closed without merging**
