### PR TITLE
Added documentation pages

### PR DESCRIPTION
**Pull request by rlebre**
In this PR I propose the inclusion of two distinct documentations: 
1) Javadoc
2) OpenAPI for web services (base created in #339 and #351)

The proposal consists of the publication of two GitHub Pages, one for each type of documentation.

**1. Javadoc**
Regarding the javadoc, I added the plugin below to the root `pom.xml`. By these means, the javadoc will be generated in all submodules and aggregated in the folder `{root}/api/javadoc` during the maven `install` phase. I also added the configuration to not duplicate the documentation within the submodules folders. 
```xml
<!-- Javadoc -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>3.1.1</version>
    <inherited>false</inherited>
    <executions>
        <execution>
            <id>aggregate</id>
            <goals>
                <goal>aggregate</goal>
            </goals>
            <phase>install</phase>
            <configuration>
                <doclint>none</doclint>
                <show>public</show>
                <reportOutputDirectory>${project.basedir}/api/javadoc</reportOutputDirectory>
                <destDir>javadoc</destDir>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**2. OpenAPI** 
In the folder `{root}/api/web` were added the needed files to serve the `dicoogle_web_api.yaml` API description. The files were gathered from the [Swagger UI GitHub repository](https://github.com/swagger-api/swagger-ui) (available [here](https://github.com/swagger-api/swagger-ui/tree/master/dist) and changed so the yaml descriptor in the website matches our descriptions.

Preliminary tests were made and are available [here](https://rlebre.github.io/dicoogle-api/) (Repository [here](https://github.com/rlebre/dicoogle-api)).

Although there is the [Dicoogle Learning Pack](https://bioinformatics-ua.github.io/dicoogle-learning-pack/) published already, sometimes I feel that there is missing the API description both for web services and javadoc. I believe this can be published and referenced later on in Learning Pack (Cc @Enet4).

### CODE REVIEW

**Comment by rlebre** [comment]
After the creation of the PR, I noticed that the GitHub pages only allow the publication of either the entire master branch or the /docs folder in the master branch. Due to this fact, I proceeded to the renaming of the `api` folder to `docs`.

**Comment by Enet4** [comment]
This approach clutters the main upstream branches with documentation. I would recommend that (1) we still keep it in a separate GitHub Pages branch, like what we have right now and (2) automate the doc generation process via CI. I propose something like this:

1. Have a new `dochub` branch with the base static site implementation of the Dicoogle documentation hub, with local stub links to Javadoc and OpenAPI, plus external links to the Learning Pack.
2. Add some steps in CI to build the documentation pages and push everything together to  `gh-pages`. Use Travis CI, or GitHub Actions if you can't get it done with Travis (ask @bastiao if you need some kind of permission token for CI to push these objects to the repository). In an initial phase, the source code to document could be fetched from the dev branch, but supporting multiple versions of Dicoogle would be interesting as well.

**Comment by rlebre** [comment]
You are absolutely right. I didn't notice that the javadoc generation during the `mvn install` would flood the git the upstream. 

My suggestion is to create a separate repository containing both documentation and generation script, simply pulling the subrepository dicoogle and generating the files. That way, we still could make use of GitHub pages to host the documentation. What do you think?

**Comment by Enet4** [comment]
Yes, that may well be more manageable. :+1:

**Comment by rlebre** [comment]
As discussed, these suggestions are now available at https://github.com/bioinformatics-ua/dicoogle-api.

To keep tracking all Dicoogle versions, I suggest that each version TAG and master/dev branches have the API updated. This means both javadoc and openapi yaml in the root folder.

**Comment by Enet4** [comment]
Is there something you would like to merge to the main repository on this subject, or this PR can be closed?

**Comment by rlebre** [comment]
As the documentation pages were deployed in https://github.com/bioinformatics-ua/dicoogle-api, this PR can be closed.

**Pull request closed without merging**
