### PR TITLE
Feature/api

### PR DESCRIPTION
**Pull request by fredericojssilva**
Falta os serviços de start & stop de serviços e plugins.
Falta tambem rever a compliance com QIDO.RS

### CODE REVIEW

**Comment by Enet4** [comment]
I have seen the new code using custom HTTP status messages, which is a bad practice. Do you have the full API described somewhere? Perhaps writing it in the wiki would be quite useful.

**Comment by bastiao** [comment]
Indeed, it is a good idea.
Check it out and feel free to give your contributions: 
https://docs.google.com/document/d/1w9OP5zct-K7Ln1zsvvrEf0xfEkYLPyTQ_ihiq4O13qA/edit?usp=sharing

**Comment by bastiao** [comment]
@fredericojssilva can you finish the QIDO-RS, and the missing services of the plugin? To merge the pull request?

**Comment by Enet4** [comment]
One of my concerns is how errors are being handled right now. If the underlying format standard does not contemplate such cases, then we should at the very least have a dedicated data type like a `{code,message}` tuple.

**Comment by Enet4** [comment]
@fredericojssilva I've started a [wiki page](https://github.com/bioinformatics-ua/dicoogle/wiki/Dicoogle-Web-Service-API) for the API.

**Comment by bastiao** [comment]
Folks, it is better to merge this branch. 
It will be easier for other branches pick the changes directly from dev. What do you think?

**Comment by bastiao** [comment]
Following our F2B discussion, we decided to merge.

**Pull request merged**
