### PR TITLE
Migrate to slf4j

### PR DESCRIPTION
**Pull request by Enet4**
Modifies dicoogle, SDK and SDK-ext in order to use the slf4j API. All direct calls to JUL and log4j were replaced (some `System.out/err` still remain, though).

### CODE REVIEW

**Comment by Enet4** [comment]
Just a heads up: the default configuration file is now at "dicoogle/src/main/resources/log4j2.xml", logging to the console and to to the file "dicoogle.log". The configuration file can be changed at deployment time with the `log4j.configurationFile` environment variable.

Unless you really think this is not ok, we are ready to merge.

**Comment by bastiao** [comment]
Seems nice. I think the log4j.configurationFile is fine as we can change in environment variable.

It raise a new problem with this branch. Any idea why? Comparing with dev branch it does not happens. It quite weird.   


```INFO  plugins.PluginController (PluginController.java:148) - Initialized plugins
ERROR users.UsersXML (UsersXML.java:142) - users.xml (No such file or directory)
java.io.FileNotFoundException: users.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[?:1.7.0_10-ea]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.7.0_10-ea]
	at java.io.FileInputStream.<init>(FileInputStream.java:97) ~[?:1.7.0_10-ea]
	at pt.ua.dicoogle.server.users.UserFileHandle.getFileContent(UserFileHandle.java:128) ~[dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.server.users.UsersXML.getXML(UsersXML.java:122) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.rGUI.server.Login.<init>(Login.java:60) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.rGUI.server.Login.getInstance(Login.java:53) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.rGUI.server.GUIServer.<init>(GUIServer.java:71) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.Main.LaunchDicoogle(Main.java:291) [dicoogle.jar:1.0-SNAPSHOT]
	at pt.ua.dicoogle.Main.main(Main.java:114) [dicoogle.jar:1.0-SNAPSHOT]
Host: localhost
```

**Comment by Enet4** [comment]
That should be fixed now.

**Comment by Enet4** [comment]
I have analysed the situation a bit further.
The one issue behind the whole-file modifications are **different line endings**. Some of our files still have CRLF endings, and the conversion tool might have modified those to LF's.
Luckily, git has a way to [ignore them when merging](http://stackoverflow.com/a/9784089/1233251), as well as to [configure the client and the repository](https://help.github.com/articles/dealing-with-line-endings/) in order to handle these issues nicely. So, we do have a need to define some guidelines in our coding style. But the only real issue in this code are line endings that will be free from serious conflicts if other people do the merge right.

[Compare dev .. imp/use_slf4j](https://github.com/bioinformatics-ua/dicoogle/compare/dev...imp/use_slf4j) 
[Compare dev .. imp/use_slf4j ignoring whitespace](https://github.com/bioinformatics-ua/dicoogle/compare/dev...imp/use_slf4j?w=1)

**Pull request merged**
