### PR TITLE
Refactor login and user session handling to address login issues

### PR DESCRIPTION
**Pull request by Enet4**
This PR fixes issues in the user store and related pages that was resulting in multiple HTTP login requests and errors when attempting to load a session in local storage.

@rlebre: Can you check whether this fixes or helps on menu webplugins not being loaded properly (#249)? I haven't tested this for users in multiple roles yet.

### CODE REVIEW

**Comment by rlebre** [comment]
As far as I tested, it seems like this pull request fixes #249 (not tested in multiple roles) with menu webplugins being loaded right as expected

**Comment by bastiao** [comment]
The first impact with the page:  Login Failed. Please try again. 

Any idea why?

(Tested with Firefox)


firsttime

**Comment by Enet4** [comment]
I'm afraid I can't reproduce. Did the console print any errors? Is the server running? What login credentials have you tried?

A JavaScript error occurs when pressing the Login button with and empty username and password, but that's fixed in #301.

**Comment by Enet4** [comment]
@bastiao Ok, I found it right now. It only happens on Firefox. I'll look into it now.

**Pull request merged**
