### PR TITLE
fix Docker build error

### PR DESCRIPTION
**Pull request by lgiancaUTH**
fix Docker build error

### CODE REVIEW

**Comment by Enet4** [comment]
I just tried the current edition of the Dockerfile and it works fine. It is not at all necessary to install Node.js and npm in the container to build Dicoogle.  What build error had occurred exactly?

**Comment by lgiancaUTH** [comment]
Dear Eduardo,

This was the error I was running into:
```
"npm ERR! cb() never called!"
```

when your tried to rebuild it are you sure you cleaned your cache?

**Comment by Enet4** [comment]
> when your tried to rebuild it are you sure you cleaned your cache?

To the best of my knowledge, no caches are ever shared into the container. There was also no caching from Docker itself (`--no-cache`). All dependencies were fetched from the Maven repositories at docker build time, including the download of an embedded Node.js and npm ecosystem (via the [frontend maven plugin](https://github.com/bioinformatics-ua/dicoogle/blob/dev/dicoogle/pom.xml#L244-L292)). Effectively, installing npm at the container is not necessary and is not something one would want to do here.

I tested it on multiple machines now. It is not possible to provide more assistance here without more details about your machine.

**Comment by lgiancaUTH** [comment]
OK, I thought my comment could be of help. Feel free to reject the change.

For reference, this was built on Docker version 20.10.10 on a Mac.

From: Eduardo Pinho ***@***.***>
Date: Tuesday, December 14, 2021 at 12:06 PM
To: bioinformatics-ua/dicoogle ***@***.***>
Cc: Giancardo, Luca ***@***.***>, Author ***@***.***>
Subject: Re: [bioinformatics-ua/dicoogle] fix Docker build error (PR #539)

**** EXTERNAL EMAIL ****

when your tried to rebuild it are you sure you cleaned your cache?

To the best of my knowledge, no caches are ever shared into the container. There was also no caching from Docker itself (--no-cache). All dependencies were fetched from the Maven repositories at docker build time, including the download of an embedded Node.js and npm ecosystem (via the frontend maven plugin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bioinformatics-2Dua_dicoogle_blob_dev_dicoogle_pom.xml-23L244-2DL292&d=DwMCaQ&c=bKRySV-ouEg_AT-w2QWsTdd9X__KYh9Eq2fdmQDVZgw&r=DDXbk7Q-SfAsJ6lnahZdDQKkpVmeygOc6oqzEyQ7ffM&m=7AtKDDIXiHGr7NetBSF-AJU4RMICT_tUjkxkQhM0uUc&s=SK0x_1UfLUIEZ2Q_9syHDiqDzG4WpNpW7BEPAkL-crI&e=>). Effectively, installing npm at the container is not necessary and is not something one would want to do here.

I tested it on multiple machines now. It is not possible to provide more assistance here without more details about your machine.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bioinformatics-2Dua_dicoogle_pull_539-23issuecomment-2D993842030&d=DwMCaQ&c=bKRySV-ouEg_AT-w2QWsTdd9X__KYh9Eq2fdmQDVZgw&r=DDXbk7Q-SfAsJ6lnahZdDQKkpVmeygOc6oqzEyQ7ffM&m=7AtKDDIXiHGr7NetBSF-AJU4RMICT_tUjkxkQhM0uUc&s=LLwn85nWwYdnCtm-t9pkVcJxeg_x5dbnTVGgrMkLzNM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHKUT4TOIAR5HIFP2ICFBGDUQ6BSXANCNFSM5JFIJUSA&d=DwMCaQ&c=bKRySV-ouEg_AT-w2QWsTdd9X__KYh9Eq2fdmQDVZgw&r=DDXbk7Q-SfAsJ6lnahZdDQKkpVmeygOc6oqzEyQ7ffM&m=7AtKDDIXiHGr7NetBSF-AJU4RMICT_tUjkxkQhM0uUc&s=LnuseHzuR4sjgq6GXyfM2pAMv0fL_OWnm5rQpmBHei0&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=bKRySV-ouEg_AT-w2QWsTdd9X__KYh9Eq2fdmQDVZgw&r=DDXbk7Q-SfAsJ6lnahZdDQKkpVmeygOc6oqzEyQ7ffM&m=7AtKDDIXiHGr7NetBSF-AJU4RMICT_tUjkxkQhM0uUc&s=MB1sGa85KrIS0ngU9lcQpsKS-6k4EBawWj058yPhr-o&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=bKRySV-ouEg_AT-w2QWsTdd9X__KYh9Eq2fdmQDVZgw&r=DDXbk7Q-SfAsJ6lnahZdDQKkpVmeygOc6oqzEyQ7ffM&m=7AtKDDIXiHGr7NetBSF-AJU4RMICT_tUjkxkQhM0uUc&s=YGULH5k1pPoqhhPNSPYQnHr3Mo3FQe6TnTLojZODdAA&e=>.

**Pull request closed without merging**
