### PR TITLE
Web UI Plugin support - Dicoogle Web Core + test plugins

### PR DESCRIPTION
**Pull request by Enet4**
This PR introduces the architecture for an extendable web UI interface (#20).

- Added web plugin management to Dicoogle.
- Added a web service for retrieving the web UI plugins.
- Added Dicoogle Web Core, a JavaScript module for loading web UI plugins and exposing them an API. 
- Some sample plugins are provided (they must be installed locally beforehand, by passing the full directory to the WebPlugins base directory.

### CODE REVIEW

**Comment by bastiao** [comment]
Very nice work. I really believe that it will be really useful in Dicoogle future. 
Comments: 
```
return "{\"plugins\":[" + String.join(",", pkgList) + "]}";
```

Probably it can work (you need to check): 
```
return "{\"plugins\":[" + StringUtils.join( pkgList, ",") + "]}";
```

Please, use compatible syntax with JDK 7, since it lives in Dicoogle. 

Minor issues that does not blocks the merge and can be fixed in a subsequent PR, but if you reply now, it will be nice:

- why are you tracking filesizes.txt? We really need it?
- in package.json of web core why "dep/jquery.js”? are you using dep path?
- using <dicoogle-slot> seems nice. but why use a new tag instead of a single div (compatible with all browsers) and use a class or id? what are the real advantages?
- since you are using AMD, bower could be nice to fetch the dependencies dynamically  (for instance, in dicoogle-webcore/test)? 
- Putting some information to test the demo/test in the dicoogle-webcore/test will be nice. You guide the developers to do one new module, but it still confusing to learn, how to run and test it.

**Comment by Enet4** [comment]
Yeah, thanks for the pointers.

- Yeah, that isn't needed. I will get rid of it in the next commit.
- That used to be a dependency, but not anymore. I've scratched that off for the next commit.
- The use of custom elements is compatible in HTML5, and can bring some potential in the long run. For instance, we can easily detect whether an element with this tag was attached. 
- I don't use bower. Does that run in the browser? Otherwise, what exactly are you suggesting? All the matter of dynamic module loading and dependency management has been a concern to me, and a tough one to get it right.
- The goal of the test chamber was to do just that. I'll see what I can do.

**Comment by bastiao** [comment]
Answer to point 3: Ok. 
Answer to point 4: dependency management to dicoogle-webcore/test. Not seeing the point of have all dependencies there (you can use the npm as well I guess).
Answer to point 5: my point was only documentation to run it or have a kind of dicoogle-webcore/demo if you prefer.  

Cheers!

**Comment by Enet4** [comment]
Sure thing, I can install dependencies with npm. But it would have been ideal to just let the plugins state what dependencies to load.

**Comment by bastiao** [comment]
Yes, make sense!

**Comment by bastiao** [comment]
Is it ready to merge?

**Pull request merged**
