### PR TITLE
Support for modifying DICOM service ports in the web app

### PR DESCRIPTION
**Pull request by Enet4**
This is the missing piece of #212.

- Refactored DICOM service management form rows into a separate component (`ServiceForm`)
- Added validation to the service port input
- Effective support for changing the port (by pressing Enter on the port field)
- Also added a loading animation while a settings change is issued

### CODE REVIEW

**Comment by bastiao** [comment]
I'm not able to test the branch. See: 
problem-services

**Comment by Enet4** [comment]
@bastiao Try updating your npm packages before building the webapp again. You might be using a version of `react-bootstrap` older than `0.29.4`.

**Comment by Enet4** [comment]
Nevertheless, that made me find another bug in the code. It's fixed in 6635fba.

**Comment by bastiao** [comment]
You added in the PR:
- logs
- netbeans configurations 
- file named webapp (probably symlink)
- other staff server-settings.xsd ? 

We need to clean up these files before merge

**Comment by Enet4** [comment]
That was definitely unintended.... I removed them now.

**Pull request merged**
